### ISSUE TITLE
Reduce number of dependencies in 'requirements.txt"

### ISSUE THREAD

**Issue by Lesbinary** [bitextor/bicleaner#1]
Hi. I don't think that all the dependencies specified right now in the 'requirements.txt' are necessary, as 'jupyter-core', 'ipython' and many other that are not even imported by any of the `bicleaner` scripts. Could you take a look at them?

**Comment by mbanon** [comment]
@Lesbinary  Sure!

**Comment by mbanon** [comment]
Fixed
