### ISSUE TITLE
Length normalization in qmax

### ISSUE THREAD

**Issue by kpu** [bitextor/bicleaner#13]
I presume the intent of length normalization in
https://github.com/bitextor/bicleaner/blob/master/bicleaner/features.py#L147
is to divide by the number of values accumulated to the log probability.  

If that is the case:
1. Why does it take `max(len(tlwords), limit)` instead of the minimum?  Why should a 2-word sentence be length normalized by 20?  
2. What about the OOV words passed by https://github.com/bitextor/bicleaner/blob/master/bicleaner/features.py#L132 ?  They appear to be included in length but not log probability, effectively giving them probability 1.

**Comment by sortiz** [comment]
Hello

> El 24 ene 2019, a las 17:53, Kenneth Heafield <notifications@github.com> escribió:
> 
> I presume the intent of length normalization in
> https://github.com/bitextor/bicleaner/blob/master/bicleaner/features.py#L147 <https://github.com/bitextor/bicleaner/blob/master/bicleaner/features.py#L147>
> is to divide by the number of values accumulated to the log probability.
> 
> If that is the case:
> 
> Why does it take max(len(tlwords), limit) instead of the minimum? Why should a 2-word sentence be length normalized by 20?

Sorry, that was my mistake. It should be min(), obviously, as you point.

logresult = float(logresult)/float(min(len(tlwords), limit))

> What about the OOV words passed by https://github.com/bitextor/bicleaner/blob/master/bicleaner/features.py#L132 <https://github.com/bitextor/bicleaner/blob/master/bicleaner/features.py#L132> ? They appear to be included in length normalization, effectively giving them probability 1.

Yes, a small probability, as log(prob) should be added instead of pass not adding anything.

if tlword not in dict_ttos:
   logresult += math.log(0.00001) # for example

**Comment by sortiz** [comment]
If after fixing this two mistakes the results will be better or worse, it’s another story. We hope it will be better.

**Comment by kpu** [comment]
Agreed we don't know if quality will be better; I suspect the model is mostly able to use the oov count feature to compensate for the second one.  
However, a model trained with one version and applied with another version will be worse.  Do you have some sort of version control on the model files to prevent cross-contamination?

**Comment by sortiz** [comment]
No, we don’t have that, but what we can do is to set it from now on, and then the  processing not having that property  will work as the current version.

**Comment by sortiz** [comment]
First tests for English-German

For 1M sentences, rank >= 0.7; before we had 90K, now we have 100K

We lost 10K mostly good sentences that before ranked just above 0.7 and now they rank just below.
We gained 20K mostly good sentences, but shorter (approx half the length on avg).
The rest of the sentences (80K) are the same.

We will try to evaluate with other language pairs to see if it’s consistent.

Maybe we could lower the threshold, or even better,  maybe we could use the evaluation results to estimate better boundaries.

**Comment by mbanon** [comment]
Fixed, tested, and updated in repository/PyPI.
