### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by lpla** [bitextor/bicleaner#14]
I run Bicleaner without the new language model feature (as I have been always running) and I got this error:

```
  File "./bicleaner/bicleaner/bicleaner_classifier_lite.py", line 272, in <module>
    main(args)  # Running main program
  File "./bicleaner/bicleaner/bicleaner_classifier_lite.py", line 265, in main
    perform_classification(args)
  File "./bicleaner/bicleaner/bicleaner_classifier_lite.py", line 254, in perform_classification
    classify(args)
  File "./bicleaner/bicleaner/bicleaner_classifier_lite.py", line 191, in classify
    if lmScore < args.lm_threshold and not args.keep_lm_result:
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

I think that some checks need to be done in this code block when no language model is given (and I guess the same for `bicleaner/bicleaner_classifier_full.py`): https://github.com/bitextor/bicleaner/blob/4051409e47e7e266a5dc3e381133f569c003362f/bicleaner/bicleaner_classifier_lite.py#L187-L201

**Comment by vitaka** [comment]
I did one last-minute refactor without properly checking that I did not break anything. Working on the fix...

**Comment by vitaka** [comment]
It should be fixed in last commit: 5676f745a2a5384e8524c0e0d7e78ff140486950

**Comment by mbanon** [comment]
Hey @lpla , 
please confirm the fix worked so we can close this issue,
thanks!

**Comment by lpla** [comment]
I confirm it works now with Bitextor. Closing.

**Comment by mbanon** [comment]
Fixed also in PyPI's Bicleaner v. 0.11.2
