### ISSUE TITLE
Creating lex files

### ISSUE THREAD

**Issue by phikoehn** [bitextor/bicleaner#17]
**Here is what I used to create the dictionary files for en-de:**

cut -f 1 train.en-de | $MOSES/scripts/tokenizer/tokenizer.perl -threads 20 -l en | $MOSES/scripts/tokenizer/lowercase.perl > train.tok.en
cut -f 2 train.en-de | $MOSES/scripts/tokenizer/tokenizer.perl -threads 20 -l de | $MOSES/scripts/tokenizer/lowercase.perl > train.tok.de

$MOSES/scripts/training/clean-corpus-n.perl train.tok en de train.clean 1 80
$MOSES/scripts/ems/support/prepare-fast-align.perl train.clean.en train.clean.de > prepared

$FAST_ALIGN -i prepared    -d -o -v > fast-align
$FAST_ALIGN -i prepared -r -d -o -v > fast-align-inverse

$MOSES/scripts/ems/support/symmetrize-fast-align.perl fast-align fast-align-inverse train.clean.en train.clean.de aligned grow-diag-final-and $MOSES/bin/symal
$MOSES/scripts/training/train-model.perl -first-step 4 -last-step 4 -f en -e de -alignment grow-diag-final-and -score-options '--GoodTuring' -lexical-file lex -alignment-file aligned -alignment-stem aligned -corpus train.clean

./filter-lex.perl < lex.e2f | gzip - > dict-de.gz
./filter-lex.perl < lex.f2e | gzip - > dict-en.gz

**The filter-lex.perl script is:**
#!/usr/bin/perl -w

use strict;

my $THRESHOLD = 0.1;

my %LEX;
while(<STDIN>) {
  chop;
  my ($a,$b,$score) = split;
  $LEX{$b}{$a} = $score;
}
close(STDIN);

foreach my $b (keys %LEX) {
  my $max = 0;
  foreach my $a (keys %{$LEX{$b}}) {
    my $score = $LEX{$b}{$a};
    $max = $score if $score > $max;
  }
  foreach my $a (keys %{$LEX{$b}}) {
    my $score = $LEX{$b}{$a};
    print "$a $b $score\n" if $score >= $THRESHOLD * $max;
  }
}

**Does this look about right?**

**Note: when doing this for en-de for the provided train.en-de data, I get 10 times smaller dict files than the ones that you provide there. Am I right to assume that yours are trained on more data?**

**Comment by sortiz** [comment]
Hello Philipp

What we used is the pre-aligned files available in Opus but we filter out not just probabilities <0.1, but probabilities <0.1 * max({p_trans(word)}) instead (if I understand your perl code, which in the case of perl it’s always challenging), if I remember correctly.

But it would be interesting to look at how it works that way because I presume the dictionaries will be smaller.

Sergio

**Comment by phikoehn** [comment]
I am doing the filtering just as you describe. For the provided train data, the dictionaries are smaller, but for WMT sized data, the dictionaries are similar size.

**Comment by mbanon** [comment]
@phikoehn Which size is "WMT sized data"?
If I remember correctly, for en-de we built the dictionaries from DGT (3.2M sentences), OpenSubtitles2018 (24.4M) and News-Commentary11 (200K)
