### ISSUE TITLE
math domain error bug fix

### ISSUE THREAD

**Issue by owenljn** [bitextor/bicleaner#19]
The bug is located in line 143 of function feature_dict_max.

This bug occurs if the source language word-target language word pair is not found in dictionary file, the probability will be zero, then the math.log(prob) would generate a math domain error, I've attached my fix below, and the code efficiency is improved by a little where math.log is called for only once

    
    if treat_oovs:
        for tlword in tlwords2[0:limit]:
            if tlword not in dict_ttos:
                if fv >= 2:
                    logresult += math.log(0.0000001)
                else:
                    pass # old behavior (it was a bug)
            else:
                t = [dict_stot.get_prob_alpha(slword, tlword) for slword in slwords_s_a]
                t.extend([dict_stot.get_prob_nonalpha(slword, tlword) for slword in slwords_s_n])
                prob = max(t, default = dict_stot.smooth)
            prob_product *= prob if prob !=0 else 1
        logresult += math.log(prob_product)
    else:
        for tlword in tlwords2[0:limit]:
            t = [dict_stot.get_prob_alpha(slword, tlword) for slword in slwords_s_a]
            t.extend([dict_stot.get_prob_nonalpha(slword, tlword) for slword in slwords_s_n])
            prob = max(t, default = dict_stot.smooth)
            prob_product *= prob if prob !=0 else 1
        logresult += math.log(prob_product)
            

    if normalize_by_length:
        if fv >= 2:
            logresult = float(logresult)/float(max(1, min(len(tlwords), limit))) # the max is to prevent zero division when tl sentence is empty        
        else:
            # old behavior (it was a bug)
            logresult = float(logresult)/float(max(len(tlwords), limit))

    return math.exp(logresult)
`

**Comment by sortiz** [comment]
Thank you for your report. I have a concern, please help me to fully see what the problem is: if `dict_stot.smooth > 0`, then `prob` can never be zero, (which is always the case). It is true that it is far away in the code.

```python
prob = max(t, default = dict_stot.smooth)
logresult += math.log(prob)
```

**Comment by owenljn** [comment]
Thanks for your clarification regarding usage of logarithm.

As for the dict_stot.smooth, I do have my dictionary containing prob equals to 0, this results in self.minprob being set to zero during the dictionary loading process, which then sets self.smooth equal to zero.

**Comment by sortiz** [comment]
I would recommend you to remove those entries or to replace the 0s with a positive number really low, like 0.0000001 or less. Alternatively, we could include this behaviour in the dictionary class when loading the values.

**Comment by owenljn** [comment]
Thanks for your reply, the zeros are generated by moses, it would be great if you can include this behaviour in the dictionary class, so the code would be perfect.

**Comment by sortiz** [comment]
Please use this at [prob_dict.py, line 29](https://github.com/bitextor/bicleaner/edit/master/bicleaner/prob_dict.py)

```python

 def load(self,fd):
        for line in fd:
            line  = line.rstrip("\n")
            parts = line.split()
            l1    = parts[1]
            l2    = parts[0]
            prob  = float(parts[2])
            if prob <= 0.0000001:
                continue
            if not self.alpha.match(l1):
                continue
            if prob < self.minprob:
                self.minprob = prob
            if l1 not in self.d:
                self.d[l1] = dict()
            self.d[l1][l2] = prob
```

It will take a while until we perform this modification, we need to test it extensively.
Thank you.
