### ISSUE TITLE
Delete/reset/rebase the commits with the language data from remote repository

### ISSUE THREAD

**Issue by Lesbinary** [bitextor/bicleaner#2]
Hi again. I am downloading this project and it takes like 15 minutes with 20Mb Internet connection because of old commits with the data of "bitextor-data/bicleaner". Could you please try to delete the old commits (IDK how, if reset or rebase would be enough) to avoid that? Thanks!

**Comment by mbanon** [comment]
@Lesbinary Sure, let me take a look into it

**Comment by mbanon** [comment]
@Lesbinary Since the first commit of the repo is the one that contains the huge data files, maybe it's easier/faster to remove the whole repo and start it again. What do you think?
