### ISSUE TITLE
Update version in pypi

### ISSUE THREAD

**Issue by alexkillen** [bitextor/bicleaner#21]
Just FYI, the version in pypi (0.11.9) still uses scipy 1.0.0, and doesn't include the fix in commit 58f5a5849193aa65a11d76f144f7b2e981f9d846 so it doesn't work with Python 3.7.

Any idea when this fix will be in pypi?

**Comment by mbanon** [comment]
Hi @alexkillen,
thanks for your feedback.
Bicleaner 0.12 will be launched during the next days.
I hope we will able to make that version work with Python3.7, but if not, we'll do the change as soon as posible in the upcoming weeks.
-Marta
