### ISSUE TITLE
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23

### ISSUE THREAD

**Issue by lpla** [bitextor/bicleaner#25]
Using `bicleaner_train`, `bicleaner_train_lite`, `bicleaner_classifier_full` or `bicleaner_classifier_lite`, scikit-learn throws a deprecation warning, suggesting that joblib should be installed directly.
```
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
```

Joblib should be added to requirements.txt and those `bicleaner` scripts should be refactored to refer to the joblib package where appropriate.

**Comment by javier171188** [comment]
How do I have to import in order to avoid that warning?

**Comment by mbanon** [comment]
Hi @javier171188 , Bicleaner 0.13 (released today in the master branch) has this dependency fixed.

**Comment by naveenbharadwaj19** [comment]
`DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.`

i'm facing the same issue how to fix this ? what does this error saying ?

**Comment by ZJaume** [comment]
Maybe you are using models trained with Bicleaner 0.12 and below, so the `.classifier` files were created with sklearn-0.21. You should use Bicleaner v0.13 and Bicleaner models v1.3, or in case you are using your own models train them again with Bicleaner 0.13.

**Comment by xpertasks** [comment]
+1
