### ISSUE TITLE
Consider sacremoses

### ISSUE THREAD

**Issue by kpu** [bitextor/bicleaner#35]
https://github.com/bitextor/bicleaner/blob/db9ca2498f6fd733d8237f5c075c6dbf892c53e3/bicleaner/util.py#L103

There is a python port of the Moses tokenizer: https://github.com/alvations/sacremoses .  Might want to check it does exactly the same thing.  But it will probably improve performance relative to feeding one line at a time across pipes.

**Comment by ZJaume** [comment]
Yeah, I was considering that since I discovered the repo, but it seems that there are still issues to solve (https://github.com/alvations/sacremoses/issues/43)

**Comment by mbanon** [comment]
Hi, I've been doing some tests comparing Bicleaner using mosestokenizer and using sacremoses.

Sacremoses is, as expected, faster than mosestokenizer:

* Old: 40.5K sents/sec (avg)
* New: 46.7K sents/sec (avg)

**Comment by mbanon** [comment]
Integrated into Bicleaner 0.14 :ok_hand:
