### ISSUE TITLE
Porn sentences through bicleaner

### ISSUE THREAD

**Issue by jgcb00** [bitextor/bicleaner#50]
Hi,
Here is a file of 10 000 porn sentences that went through bicleaner en_nl v0.14 en were not flag.

Hope that it can help,
[biclean_porn.txt](https://github.com/bitextor/bicleaner/files/5628825/biclean_porn.txt)

**Comment by ZJaume** [comment]
That's nice, thank you so much. I'll append to the current porn_removal training file for the next release, hopefully it will improve performance for the classifier.

**Comment by jgcb00** [comment]
Hi,
I went through a manual review of the file and find out that my grep was a bit to agressive.
So I make an manual check and come out with 2 files, one wich sexual non pornographic senteces and one with pornographic sentences. Hope it will help you. 

I don't have the time to make the 10'000 sentences review.


[porn_bicleaner.txt](https://github.com/bitextor/bicleaner/files/5716629/porn_bicleaner.txt)
[no_porn_bicleaner.txt](https://github.com/bitextor/bicleaner/files/5716630/no_porn_bicleaner.txt)

**Comment by ZJaume** [comment]
The porn removal classifier was introduced to remove only explicit porn and not profanity. So, this is helpful, thanks!
