### ISSUE TITLE
bicleaner-classify cannot serialize '_io.TextIOWrapper'

### ISSUE THREAD

**Issue by pmoda** [bitextor/bicleaner#52]
Hi, I am trying to run a simple biclearner classify on some english-french data.
Using Windows and Python 3.7 and the command in this format:
.../bicleaner-classify ...\test2.tmx ...\en-fr\en-fr.yaml

I am getting the following message:
```
Traceback (most recent call last):
  File "D:/Git/bicleaner/scripts/bicleaner-classify", line 20, in main
    classifier.main(args)  # Running main program
  File "D:\Git\bicleaner\bicleaner\bicleaner_classifier_full.py", line 445, in main
    perform_classification(args)
  File "D:\Git\bicleaner\bicleaner\bicleaner_classifier_full.py", line 393, in perform_classification
    reduce.start()
  File "D:\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.TextIOWrapper' object
```
I looked around and there were mentions of this being caused by the logger, tried commenting all references with no change. 
Also tried bicleaner-classify-lite but got different error messages.

Any help would be really appreciated as this project sounds very interessting!

Thank you,

Patrick

**Comment by mbanon** [comment]
Hi Patrick,
we are happy that you find Bicleaner interesting :)

Regarding your issue, you are apparently trying to run Bicleaner on a TMX file. This is not supported, you need to extract parallel text from the TMX and run Bicleaner on the parallel text. To extract parallel text from the TMX file, you can use this tool https://github.com/sortiz/tmxt

Please let us know if this worked :)

PS: Bicleaner has not been tested on Windows, I 'd suggest to run it on Linux, if you have the chance.

**Comment by pmoda** [comment]
Great! the parallel format worked.

Note: I had to specify encoding="utf-8" for input-output-metadata arguments for it to work
and never got the full version to work on Windows, only the Lite (which is good enough for me)

Thank you so much for your help!

**Comment by mbanon** [comment]
Great to know it worked for you!
Please don't hesitate to open a new issue if you need further help :)
