### ISSUE TITLE
Issue with training a bicleaner model

### ISSUE THREAD

**Issue by jgcb00** [bitextor/bicleaner#53]
Hi,
I tried to train a bicleaner model for fr-nl, I am on the last docker version, and in bicleaner repo I made `git checkout bicleaner-0.14`. I used bicleaner version 0.14 for months without any issue.

For the first time I'm trying to train a model, and I'm struggling. 

On the last step: 
```
root@b7cea87001cb:/home/bitextor/bicleaner-model/fr-nl# ls
dict-fr.gz  dict-nl.gz  fr-nl.classifier  fr-nl.yaml  porn-annotated.txt.fr  porn-model.fr  smallcorpus  wordfreq-fr.gz  wordfreq-nl.gz
root@b7cea87001cb:/home/bitextor/bicleaner-model/fr-nl# python3 /opt/bitextor/bicleaner/bicleaner/bicleaner_train.py \
>     smallcorpus \
>     --normalize_by_length \
>     -s fr -t nl \
>     -d dict-fr.gz -D dict-nl.gz \
>     -b 1000 -c fr-nl.classifier \
>     -f wordfreq-fr.gz -F wordfreq-nl.gz \
>     -m fr-nl.yaml \
>     --lm_file_sl model.fr-nl.fr  --lm_file_tl model.fr-nl.nl \
>     --porn_removal_train porn-annotated.txt.fr  --porn_removal_file porn-model.fr --relative_paths
2021-03-03 19:46:22,171 - INFO - Training porn removal classifier.
2021-03-03 19:46:43,145 - INFO - Compressing classifier.
2021-03-03 19:48:11,863 - INFO - Saving porn removal classifier.
2021-03-03 19:48:11,889 - INFO - Training LM-based fluency filter.
2021-03-03 19:48:11,889 - INFO - SL & TL LM training corpora have been obtained from tab-separated input file (the same ones used for training the classifier), after randomly removing 2000 sentences.
2021-03-03 19:48:11,889 - INFO - SL & TL LM dev clean corpora have been randomly selected from input input file (the same used for training the classifier): 2000 sentences.
2021-03-03 19:48:34,908 - INFO - SL LM dev noisy corpus: /tmp/tmptj77h9ld
2021-03-03 19:48:47,028 - INFO - TL LM dev noisy corpus: /tmp/tmp2p_pecdr
Loading the LM will be faster if you build a binary file.
Reading /tmp/tmpofyh5nn2
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
Traceback (most recent call last):
  File "kenlm.pyx", line 128, in kenlm.Model.__init__
RuntimeError: End of file Byte: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 232, in train
    self.sl_filter.train_lm(lm_train_sl)
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 154, in train_lm
    self.lm=kenlm.LanguageModel(self.lm_path)
  File "kenlm.pyx", line 131, in kenlm.Model.__init__
OSError: Cannot read model '/tmp/tmpofyh5nn2' (End of file Byte: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_train.py", line 523, in <module>
    main(args)
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_train.py", line 519, in main
    perform_training(args)
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_train.py", line 402, in perform_training
    stats=train_fluency_filter(args)
  File "/opt/bitextor/bicleaner/bicleaner/training.py", line 116, in train_fluency_filter
    stats=ff.train(lm_train_path_sl, lm_train_path_tl,lm_dev_clean_sl,lm_dev_clean_tl, args.noisy_examples_file_sl,args.noisy_examples_file_tl, args.lm_file_sl, args.lm_file_tl)
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 241, in train
    self.tl_filter.cleanup()
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 164, in cleanup
    os.remove(self.lm_path)
AttributeError: 'LMFluencyFilter' object has no attribute 'lm_path'
```
It 's working when I remove the : `--lm_file_sl model.fr-nl.fr  --lm_file_tl model.fr-nl.nl` options.

On the tutorial you gave, there are `--lm_training_file_sl lmtrain.en-is.en --lm_training_file_tl lmtrain.en-is.is` but it's not working in my case, because I don't have these files, and I don't know how to generate them. 

Thanks for your help,

Jean-Gabriel

**Comment by ZJaume** [comment]
Hi Jean-Gabriel

I guess that the error is because you are using the `--lm_file*` and it is attempting to train the character language model without the training files. The language model is optional, so you can remove those options. Otherwise, if you want the language model, you only need monolingual sentences in the source and target language in separated files. You can get those sentences from your parallel corpus or any monolingual source of your choice.

**Comment by jgcb00** [comment]
Ok, does the model improve the performance of bicleaner ? What is it use for ?

**Comment by ZJaume** [comment]
It is a 7-gram character language model used as a hardrule to filter out ugly sentences. It is useful when you are dealing with very noisy data from the web but still removes sentences that could be good. My advice is to train it because it is cheap and then you can disable during the classifying process with `--disable_lm_filter` in cas you don't want it. To see if the LM filter is useful to you, you can run hardrules separately to see if the LM or other hardrule removes sentences you want to keep.

With `--annotated_output` you can see which rule is being applied to discard each sentence and then disable the LM or another rule that can be disabled.
```
  --disable_lang_ident  Don't apply rules that use language detecting
                        (default: False)
  --disable_minimal_length
                        Don't apply minimal length rule (default: False)
  --disable_porn_removal
                        Don't apply porn removal (default: False)
```

Another thing you can do is count the number of sentences discarded by each rule
```bash
bicleaner-hardrules --metadata your-model-path/fr-nl.yaml --annotated_output input.fr-nl - \
   | LC_ALL=C sort | uniq -c
  ```

**Comment by jgcb00** [comment]
Ok thank you very much, how many sentences is recommended  for the training of the LM model ?

**Comment by ZJaume** [comment]
With at least 200K sentences you'll probably be ok

**Comment by ZJaume** [comment]
Another advise that I could give you is to disable minimal length rule if you are gonna train NMT only with the sentences filtered by Bicleaner. Otherwise your model could end up having poor performance with short sentences if you don't have samples with 1/2/3 words in a sentence.

**Comment by jgcb00** [comment]
Yes I made y own version of bicleaner hardrules deleting all regex that I found not usefull. 
Thank you very much for your help i keep you updated if the training fail.

**Comment by jgcb00** [comment]
I have the same issue with the two files, 
```
Traceback (most recent call last):
  File "kenlm.pyx", line 139, in kenlm.Model.__init__
RuntimeError: End of file Byte: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 232, in train
    self.sl_filter.train_lm(lm_train_sl)
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 154, in train_lm
    self.lm=kenlm.LanguageModel(self.lm_path)
  File "kenlm.pyx", line 142, in kenlm.Model.__init__
OSError: Cannot read model '/tmp/tmp5g529osn' (End of file Byte: 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_train.py", line 523, in <module>
    main(args)
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_train.py", line 519, in main
    perform_training(args)
  File "/opt/bitextor/bicleaner/bicleaner/bicleaner_train.py", line 402, in perform_training
    stats=train_fluency_filter(args)
  File "/opt/bitextor/bicleaner/bicleaner/training.py", line 116, in train_fluency_filter
    stats=ff.train(lm_train_path_sl, lm_train_path_tl,lm_dev_clean_sl,lm_dev_clean_tl, args.noisy_examples_file_sl,args.noisy_examples_file_tl, args.lm_file_sl, args.lm_file_tl)
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 241, in train
    self.tl_filter.cleanup()
  File "/opt/bitextor/bicleaner/bicleaner/lm.py", line 164, in cleanup
    os.remove(self.lm_path)
AttributeError: 'LMFluencyFilter' object has no attribute 'lm_path'

```

**Comment by ZJaume** [comment]
Could you post the full command?

**Comment by ZJaume** [comment]
Hi again,

Remembered that those errors usually occur when KenLM is not correctly installed (check that you pointed to the right python environment with `-DCMAKE_INSTALL_PREFIX` whern installing it) or because KenLM is running out of memory. Unfortunately, 0.14 version does not print the stderr output of KenLM if it fails, but I've added a commit to the `bicleaner-0.15` branch that prints the output in case KenLM fails.

**Comment by jgcb00** [comment]
Hi, 
this is my command : 
```
python3 /opt/bitextor/bicleaner/bicleaner/bicleaner_train.py \
    smallcorpus \
    --normalize_by_length \
    -s fr -t nl \
    -d dict-fr.gz -D dict-nl.gz \
    -b 1000 -c fr-nl.classifier \
    -f wordfreq-fr.gz -F wordfreq-nl.gz \
    -m fr-nl.yaml \
    --lm_training_file_sl lmtrain.fr-nl.fr --lm_training_file_tl lmtrain.fr-nl.nl \
    --lm_file_sl model.fr-nl.fr  --lm_file_tl model.fr-nl.nl \
    --porn_removal_train porn-annotated.txt.fr  --porn_removal_file porn-model.fr --relative_paths
```
```
$ ls
dict-fr.gz  dict-nl.gz  fr-nl.classifier  fr-nl.yaml  LMmodel  lmtrain.fr-nl.fr  lmtrain.fr-nl.nl  log_training  porn-annotated.txt.fr  porn-model.fr  smallcorpus  wordfreq-fr.gz  wordfreq-nl.gz
```
Okay, i was expecting that KenLM was correctly install since it's on the docker but I will check that.

**Comment by jgcb00** [comment]
So i reinstalled kenlm from scratch in the docker and it's still not working. I switched to 0.15 branches.  
```
2021-03-09 14:57:54,959 - ERROR - KenLM is not installed, please check Bicleaner installation instructions on how to do so. If you already done this, check that the -DCMAKE_INSTALL_PREFIX:PATH points to your environment path.
2021-03-09 14:57:54,959 - ERROR - stderr: /bin/sh: 1: lmplz: not found
```
So maybe I didn't run with the right prefix:
```
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/your/prefix/path
```
kelm is in `/opt/bitextor/bicleaner/bicleaner` so it's `/opt/bitextor/bicleaner/bicleaner/kenlm/` or `/opt/bitextor/bicleaner/bicleaner/kenlm/build` ?

**Comment by ZJaume** [comment]
The prefix path is path to your python environment or any other path where the system places binaries. In the case of a docker image, it could be `/usr/bin`, I guess.

**Comment by jgcb00** [comment]
It 's still not working neither as /bin, from my investigation, I found out that the script is looking for lmplz wich is in my `/opt/bitextor/bicleaner/bicleaner/kenlm/bin/` file, so he is not looking at the right place.
Switching to bicleaner-0.15 did'nt help

**Comment by ZJaume** [comment]
Have followed all the steps for KenLM installation?

```
git clone https://github.com/kpu/kenlm
cd kenlm
python3.7 -m pip install . --install-option="--max_order 7"
mkdir -p build && cd build
cmake .. -DKENLM_MAX_ORDER=7 -DCMAKE_INSTALL_PREFIX:PATH=/your/prefix/path
make -j all install
```

In your case, if you are not installing bicleaner in a virtual environment, you could omit use as prefix any of `/usr/bin` or `/bin`, or directly omit the `-DCMAKE_INSTALL_PREFIX` and it will default to one of those, I guess. Even so, if any of these things does not work, you could add your KenLM  install path to your $PATH environment variable:

`export PATH="$PATH:/opt/bitextor/bicleaner/bicleaner/kenlm/bin/"`

If it's correctly installed, you should be able to run the `lmplz` anywhere.

**Comment by jgcb00** [comment]
Hi, indeed the only thing missing was the export command, 
Thank you very much !
