### ISSUE TITLE
Training Corpus

### ISSUE THREAD

**Issue by hlhlpfp** [bitextor/bicleaner#57]
Hi,
I am new in Data Science field and wanted to understand more about training corpus in this case that needs to be around 100K of very clean parallel sentences in order to train the Bicleaner model. Why it needs to be super cleaned input/parameter, instead of mix data (clean and noisy sentences) ?! How the Bicleaner classifier will understand that the pair of sentences is clean or noisy if it is not trained with mix data? Is this a supervised or unsupervised method?
Thanksss

**Comment by ZJaume** [comment]
Hi @hlhlpfp,
Negative samples for supervised training are built synthetically from the input training set. So, all of the input sentences are considered positive samples, that's why you need a clean corpus. I think this responds all your questions. If you have more questions don't hesitate to ask.

**Comment by hlhlpfp** [comment]
@ZJaume,
How would l evaluate the performance of such a model? Like what is the accuracy of such model?
Thanks so much

**Comment by ZJaume** [comment]
This is a complicated question. Regarding the actual accuracy of the model, there are some precision and recall histograms stored at the metadata file after training. These are calculated over a development set extracted from the provided training set. Unfortunately, this can only be used as an indicator on whether if the model training has gone well or not. To perform an evaluation of the model you should train NMT models with the raw and filtered data with bicleaner and compare the quality of those models.

If you are interested in learning more about parallel corpus filtering and how to evaluate that, I suggest you to take a look at the [WMT task](http://www.statmt.org/wmt20/parallel-corpus-filtering.html). We participated several years using Bicleaner. There you will find more complex ways of evaluation.

**Comment by hlhlpfp** [comment]
@ZJaume Thank you. l really appreciate it

**Comment by ZJaume** [comment]
If the script is exactly what you post, it is working for me after fixing the `\ `. Check that there is no other backslash (`\`) escaping a space. I should be only at the end of the line.
