### ISSUE TITLE
Multi-machine parallelism

### ISSUE THREAD

**Issue by kpu** [bitextor/bicleaner#6]
We can't afford to wait a week for bicleaner to run on the large crawls.  Since classification decisions are independent at the sentence level, let's use multiple machines.  Can this be done with GNU `parallel --pipe` and `--sshlogin`?

**Comment by kpu** [comment]
More generally, can you separate the multiprocess stuff from the classifier in `https://github.com/bitextor/bicleaner/blob/master/bicleaner/bicleaner_classifier_full.py` so that somebody could bypass your multiprocess entirely, submit single-core slurm jobs, and aggregate later (which I think is just cat?)?

**Comment by mbanon** [comment]
@kpu 
Hi, we just released a "lite" bicleaner that has no multiprocessing at all.
We are still doing some tests to compare its performance with those of using the "full" bicleaner with the  -p1 option (that is: using only one process), but it's already available:
* Here in github: bicleaner/bicleaner_classify_lite.py
* In pypi: python3 -m pip install bicleaner (you'll get v. 0.10.5) and you'll get a "bicleaner-classify-lite" script (aside from the classical ones, "bicleaner-classify" and "bicleaner-train")
Then, run bicleaner-classify-lite input output metadata

**Comment by hieuhoang** [comment]
On a 32-core machine with the data on a network drive, this is the output from top

Tasks: 918 total,   4 running, 913 sleeping,   0 stopped,   1 zombie
%Cpu(s):  0.2 us,  0.8 sy,  7.7 ni, 91.1 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 29712016+total,  9048732 free, 67876088 used, 22019532+buff/cache
KiB Swap: 29282201+total, 28801974+free,  4802268 used. 22621641+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                  
  319 bhaddow   30  10 44.418g 679260 228484 R 100.0  0.2   1946:56 marian                                                                                                                                   
24342 s0565741  30  10 2307636 958360   4360 R  99.3  0.3  23063:15 bicleaner-class                                                                                                                          
24377 s0565741  30  10 4593660 909056  16748 S   7.3  0.3   2528:47 bicleaner-class                                                                                                                          
31869 ganglia   20   0 4951128 154484   4576 S   6.6  0.1 603:42.41 beam.smp                                                                                                                                 
24389 s0565741  30  10 4597384 912728  16752 S   4.0  0.3   2524:05 bicleaner-class                                                                                                                          
24384 s0565741  30  10 4607828 923108  16716 S   3.3  0.3   2535:12 bicleaner-class   

ie. it's not using the many cores. It might be an idea to see why it doesn't run well on 1 machine before spawning it on lots of machines

**Comment by kpu** [comment]
@hieuhoang Which is exactly why I asked them to remove their parallelization so we can use GNU parallel.  
`pv paracrawl/paracrawl-release3.en-es.gz |zcat |parallel -k --pipe python3 .local/bin/bicleaner-classify-lite - /mnt/vali0/hieu/workspace/experiment/bicleaner/en-es/training.en-es.yaml |pigz >en-es.gz`

**Comment by mbanon** [comment]
Hi, 
please check https://github.com/bitextor/bicleaner/issues/8#issuecomment-437315462

**Comment by mbanon** [comment]
Updated bicleaner lite both in repository and PyPI  (version 0.10.6)
Closing  issue.
