### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by hlhlpfp** [bitextor/bicleaner#60]
Hello,
I trained bicleaner model and got the following parameters that indicate the performance of the model, but l can't tell if it is good model or not. Based on these results what do you think?
good_test_histogram: [13, 38, 48, 98, 165, 360, 661, 1121, 1471, 1025]
wrong_test_histogram: [2270, 610, 594, 495, 461, 328, 161, 68, 11, 0]
precision_histogram: [0.5001000, 0.6464031, 0.7002972, 0.7628016, 0.8235597, 0.8908951, 0.9468792, 0.9786255, 0.9956123, 1.0000000]
recall_histogram: [1.0000000, 0.9974000, 0.9898000, 0.9802000, 0.9606000, 0.9276000, 0.8556000, 0.7234000, 0.4992000, 0.2050000]
accuracy_histogram: [0.5001000, 0.7258452, 0.7830566, 0.8376675, 0.8773755, 0.9069814, 0.9037808, 0.8537708, 0.7484497, 0.6024205]
length_ratio: 0.8593951
features_version: 4
disable_lang_ident: False

**Comment by mbanon** [comment]
Hi there, @hlhlpfp 

Looking at the accuracy histogram, you got the peak at the 6th value, that means that the optimum threshold for bicleaner is 0.5 (values in the histogram mean the accuracy when setting the threshold at 0.0, 0.1, 0.2, ..., 1.0).

That means that, when setting the threshold in 0.5, your accuracy will be aprox 0.906, wich is quite good.

Cheers,
-Marta.
