### ISSUE TITLE
Can't understand what third column(numbers generated when testing bicleaner)

### ISSUE THREAD

**Issue by hlhlpfp** [bitextor/bicleaner#61]
hi,
I trained bicleaner and then tested it. The resulting file had an extra column (as expected) with numbers between 0 and 1. 
Understanding the factors 	Bien comprendre l	0.752
will allow for tailored .	permettra d’élaborer 	0.824
Strengthen key and vulnerable	Renforcer les connaissances 	0.610
Expanded reinforcement 	Renforcement accru 	0.672
Indicate the proposed 	Indiquez le montant 	0.818

What these numbers generated exactly mean?  (0.752 0.818 0.610 0.672) . when we say 0.672 , what does it mean?
Please, if you can provide me a more detailed explanation? 
p.s i know so far that: - Sentence pairs considered very noisy are scored with 0.
                                  -    sentences being mutual translations with 1. 
 Thank you

**Comment by mbanon** [comment]
From the very second line in the readme:
`It indicates the likelihood of a pair of sentences being mutual translations (with a value **near to** 1) or not (with a value **near to** 0). `
