### ISSUE TITLE
Model Architecture

### ISSUE THREAD

**Issue by hlhlpfp** [bitextor/bicleaner#62]
hi,
Wanted to know more about model architecture. what type is it? XGBoost? SVM?

**Comment by ZJaume** [comment]
[Extremely Randomized Trees](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html)

You can see the details in the last shared task that we participated [](https://aclanthology.org/2020.wmt-1.107.pdf)
