### ISSUE TITLE
Performance improvement of bicleaner 

### ISSUE THREAD

**Issue by hlhlpfp** [bitextor/bicleaner#63]
Hi,
I have trained bicleaner and evaluated its performance. 
BTW l find it very useful. Thank you so much.
But wanted to know more about how to improve the performance of the model?

**Comment by ZJaume** [comment]
All the improvements that have been explored are used by default and reflected in the tutorials.
If yo wanna improve the model you would need to investigate by yourself.

Or use [Bicleaner Ai](https://github.com/bitextor/bicleaner-ai) which is a new version using neural networks and its full models work considerably better than Bicleaner.
