### ISSUE TITLE
Does disable_hardrules also disable_lm_filter ?

### ISSUE THREAD

**Issue by jgcb00** [bitextor/bicleaner#65]
Hi,
I was wandering,`--disable_hardrules` seems to also disable the language model filtering. Is it possible to change that?

Hard rules are really strict and most of the time I don't need them but sometimes I get an extraction big mess which the language model seems to capture well only if it's applied. 

So Is it possible that disable_hardrules doesn't disable_lm_filter? 

Thanks

**Comment by ZJaume** [comment]
We are working on a configurable [hardrules](https://github.com/bitextor/bicleaner-hardrules) that can do the trick. It won't be released yet but you can try it installing master branch.

To run with a custom configuration you have to use the `-c config.yml` to provide a YAML config.
The configurable rules are [here](https://github.com/bitextor/bicleaner-hardrules/blob/1877b5410bbedc1b60bd3f14e7c5feb7950e340c/hardrules/hardrules.py#L45).
You just need to put on the file every rule to `False` except the LM rule like this:
```yaml
no_empty: False
max_char_length: False
no_literals: False
...
```

The current published Bicleaner version (0.14) does not have the hardrules separated as an independent module but running it with `--disable_hardrules` and previously run the `bicleaner-hardrules` command after installing the standalone package should work.

**Comment by jgcb00** [comment]
Ok thanks,
Can't wait to see it working with bicleaner natively.
I will use this way in the mean time.

Thanks

**Comment by ZJaume** [comment]
Solved a bug in lm_filter in the parametrized hardrules, please if you were already using it update the master branch.

**Comment by jgcb00** [comment]
Hi,
it looks like now bicleaner-hardrules is now integrate in bicleaner, am I right ?

So I should be able to personalize the .yaml file with bicleaner rules ?

**Comment by ZJaume** [comment]
Yes, you are right.
