### ISSUE TITLE
Generic tokenizer

### ISSUE THREAD

**Issue by kpu** [bitextor/bicleaner#7]
Currently the tokenizer is hard-coded to Moses.  The user should be able to specify an arbitrary pre/post processing pipeline.  This is necessary to support e.g. Chinese and Arabic.  Admittedly outside the remit of ParaCrawl's EU languages.

**Comment by sortiz** [comment]
Would  a flag for "tokenize by whitespace" be acceptable? So that anyone can pre-tokenize corpora and then work with it.

**Comment by mbanon** [comment]
@lpla  is working on it.

**Comment by lpla** [comment]
Done

**Comment by mbanon** [comment]
plealse @lpla , fix the default tokenizer thing
