### ISSUE TITLE
Bicleaner models for Paracrawl bonus languages

### ISSUE THREAD

**Issue by MaximumEntropy** [bitextor/bicleaner#71]
Hi,

I was wondering if there are any plans to release bicleaner models for the "bonus" paracrawl languages such as Ukrainian or Chinese?

Thanks!

**Comment by mbanon** [comment]
Hi @MaximumEntropy ,

of course, we aim at publishing all the individual models trained for Bicleaner as they become available. Note that for most of the bonus languages in ParaCrawl, we did not use a language-specific model, but the multilingual one.

**Comment by MaximumEntropy** [comment]
Thanks! Can I get a link to the multilingual model and the list of languages that it supports?

**Comment by mbanon** [comment]
Sure, you must use bicleaner-ai (https://github.com/bitextor/bicleaner-ai) for the multilingual (en-xx) model. You can find all models for bicleaner-ai  here: https://github.com/bitextor/bicleaner-ai-data/releases/tag/v1.0
