### ISSUE TITLE
Conda package not up-to-date

### ISSUE THREAD

**Issue by OrianeN** [bitextor/bicleaner#80]
I've got issues when trying to install bicleaner with `pip` following your documentation - linked to FastSpell/Hunspell. Unfortunately, I cannot use `sudo` or `apt` on the cluster I'd like to install it, yet when trying the conda installation command you provided it worked (`conda install -c conda-forge -c bitextor bicleaner`).

Yet I noticed that the version installed is v0.15.2, i.e. dating back to 2022, requiring only Python3.8, and probably not including the latest features related to bicleaner-hardrules and FastSpell.

Would it be possible to publish a new conda package ?

**Comment by mbanon** [comment]
Hi @OrianeN, we'll do it as soon as possible. Will let you know when it's done :)

**Comment by mbanon** [comment]
Hi @OrianeN ! We haven't release the Conda version yet BUT I just released a new Bicleaner version (0.17.4) in Pypi with the latest hardrules and fastspell. Hopefully, you will be able to install it with your current system packages. 
If you are using Python3.10, which is known to have install issues with Fastspell, the commands to follow are the following:
```
pip install git+https://github.com/MSeal/cython_hunspell@2.0.3
pip install bicleaner==0.17.4
pip install --config-settings="--build-option=--max_order=7" https://github.com/kpu/kenlm/archive/master.zip
```
with any other Python version, you should be able to omit the explicit  cython install.

I hope it works, anyway, we'll release the Conda package soon.

**Comment by OrianeN** [comment]
Thanks @mbanon, I got it to work both locally and on the server with Python3.10 !

Btw I looked again at the error I had, and it turns out my problem was not linked to Hunspell, but the `fasttext` python package. My error looked a bit like the one at https://github.com/facebookresearch/fastText/issues/1343#issuecomment-1643621993 (except I was running it on CentOS) when trying to install `fasttext==0.9.2` (not sure I remember the exact patch version). I guess this was fixed in a more recent version of fasttext/fasttext-wheel which is now installed with `bicleaner==0.17.4`.

**Comment by ZJaume** [comment]
If conda build is no longer needed, I think I'm gonna close this. Conda builds are something that we do not have much experience nor use it frequently. Therefore I will try to avoid spending time doing releases if it is not strictly necessary.

**Comment by ZJaume** [comment]
Please @OrianeN if you have other issues don't hesitate to ask.
