### ISSUE TITLE
Add model training to bitextor snakemake

### ISSUE THREAD

**Issue by kpu** [bitextor/bicleaner#9]
The Alicante & London people have a snakemake pipeline.  This includes MT training and filtering.  But it can't built its own bicleaner models.  Really the point of the open source release is that people can run their own languages.  Can you add bicleaner training to bitextor's snakemake?

**Comment by mbanon** [comment]
Hi Ken, 
we scheduled a talk with the Alicante team to discuss how to implement this.
Cheers.

**Comment by mbanon** [comment]
@mespla  is working on it

**Comment by lpla** [comment]
Now it is done in `bitextor-malign` branch of `bitextor`, in the Snakemake pipeline.
